---
title: "Workflow for Biologist"
author: "Emilio A. Laca"
date: "6/21/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# THIS SCRIPT IS IN PROGRESS AND NOT READY FOR TESTING

## Introduction

## Data files and scripts necessary

## Workflow steps

### Collect files and scripts in dedicated directory

### Perform main analysis and obtain estimates for units and year

This step produces a series of visual and tabular outputs, and the qdt_mass_g_m2_yyyy.txt file with the following structure:

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	82 obs. of  23 variables:
 $ LIT            : chr  "CLS" "CLS" "CLS" "CLS" ...
 $ Unit_Name      : chr  "T10" "T13A" "T15" "T15" ...
 $ Subunit_Name   : chr  "T10:3" "T13A" "T15:1" "T15:2" ...
 $ subunit_ID     : chr  "CLS_T10_T10:3" "CLS_T13A_T13A" "CLS_T15_T15:1" "CLS_T15_T15:2" ...
 $ st_g_m2_a.Low  : num  77.4 77.4 77.4 77.4 77.4 ...
 $ st_g_m2_b.Med  : num  287 287 287 287 287 ...
 $ st_g_m2_c.High : num  763 763 763 763 763 ...
 $ wg_g_m2_a.Low  : num  16.9 16.9 16.9 16.9 16.9 ...
 $ wg_g_m2_b.Med  : num  53.8 53.8 53.8 53.8 53.8 ...
 $ wg_g_m2_c.High : num  68.4 68.4 68.4 68.4 68.4 ...
 $ wg_g_m2        : num  7.758 0 0.0147 0 0 ...
 $ st_g_m2        : num  173 581 429 0 0 ...
 $ tot_g_m2       : num  181 581 429 0 0 ...
 $ area_ha        : num  17.4 36 14.2 16.7 30 ...
 $ tot_mass_m2_var: num  406 7080 6116 0 0 ...
 $ CI80lwr        : num  155 473 329 0 0 ...
 $ CI80upr        : num  206 689 529 0 0 ...
 $ st_mass_m2_var : num  404 7080 6116 0 0 ...
 $ CI80lwr_st     : num  147 473 329 0 0 ...
 $ CI80upr_st     : num  199 689 529 0 0 ...
 $ wg_mass_m2_var : num  1.9572 0 0.0274 0 0 ...
 $ CI80lwr_wg     : num  5.965 0 -0.197 0 0 ...
 $ CI80upr_wg     : num  9.551 0 0.227 0 0 ...
 - attr(*, "notes")= chr "These estimates include the variance due to quadrat sampling and estimation of proportion of area covered by ea"| __truncated__


### Make tables and graphs by refuge


### Compare treatments


### Compare years


### 
