---
title: "Compare subunits across years"
author: "Emilio A. Laca"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# THIS SCRIPT SHOULD CREATE A GRAPH WITH CI's FOR YIELD IN EACH SUBUNIT EACH YEAR

## Task

Create a graph for subunits within for each refuge that includes estimated means and CI for 2019 and 2020. Include all subunits surveyed in WHAP (ie keep units that were not surveyed in one of the years on the graph).

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(tidyverse)
library(knitr)
library(kableExtra)


```


```{r prepData}

# In the future, this chunk should join all years available or
# use a file with all years that is automatically created at the server.

gm2_2019 <- read.csv("MainScriptDataOutput/qdt_mass_g_m2_2019.txt") %>%
  dplyr::select(-X) %>%
  mutate(year = 2019)

gm2_2020 <- read.csv("WHAP2020-21/Output2020/qdt_mass_g_m2_2020.txt") %>%
  dplyr::select(-X) %>%
  mutate(year = 2020)

gm2_2021 <- read.csv("WHAP2021-22/Output2021/qdt_mass_g_m2_2021.txt") %>%
  dplyr::select(-X) %>%
  mutate(year = 2021)

# 2021 column names are different than 2020 and 2019. Need to decide on a
# and edit files from past years. Different refuges also have different
# formats for subunit names in the unit and subunit name fields
colnames(gm2_2021)[1] <- "Unit_Name"
colnames(gm2_2021)[2] <- "Subunit_Name"

# Combine data for all years.
whap_su_years <- bind_rows(gm2_2019, gm2_2020, gm2_2021) %>%
  mutate(year = factor(year))

# Add new LIT name for KRN 14 subunits to create a different figure
# for these subunits. Only used for swamp timothy
# levels(whap_su_years$LIT) <- c(levels(whap_su_years$LIT), "KRN14")
# whap_su_years$LIT[whap_su_years$Unit_Name == "14"]  <- "KRN14"

# Use only 2021 for the figures (for MDC watergrass to exclude 2020 data)
whap_su_years <- gm2_2021 %>%
  mutate(year = factor(year))


```


```{r viabilityClasses}

# Stone lakes as of Jan 2022 uses Low, Medium, High, and Very_High as their
# viability analysis categories, represented by the colors "lightgoldenrod", 
# "yellow", "chartreuse", and "chartreuse3". All other refuges use Poor, Fair, 
# Good, and Very_Good for their viability analysis categories, represented by
# the colors "red", "yellow", "chartreuse", and "chartreuse3". The code below
# and the viability analysis csv files need to be adjusted accordingly.


# ST viability classes
ST_viaClass <- read.csv("WHAP_Viability_ST.csv") %>%
  pivot_longer(cols = c(Poor, Fair, Good, Very_Good),
               names_to = "class",
               values_to = "lower_bound") %>%
  pivot_wider(names_from = LIT,
              values_from = lower_bound) %>%
  mutate(class = fct_reorder(class, KRN, mean),
         class_color = c("red", "yellow", "chartreuse", "chartreuse3"),
         class = factor(class, ordered = TRUE))

# WG viability classes
WG_viaClass <- read.csv("WHAP_Viability_WG.csv") %>%
  pivot_longer(cols = c(Poor, Fair, Good, Very_Good),
               names_to = "class",
               values_to = "lower_bound") %>%
  pivot_wider(names_from = LIT,
              values_from = lower_bound) %>%
  mutate(class = fct_reorder(class, KRN, mean),
         class_color = c("red", "yellow", "chartreuse", "chartreuse3"),
         class = factor(class, ordered = TRUE))

#SW viability classes
SW_viaClass <- read.csv("WHAP_Viability_SW.csv") %>%
  pivot_longer(cols = c(Poor, Fair, Good, Very_Good),
               names_to = "class",
               values_to = "lower_bound") %>%
  pivot_wider(names_from = LIT,
              values_from = lower_bound) %>%
  mutate(class = fct_reorder(class, KRN, mean),
         class_color = c("red", "yellow", "chartreuse", "chartreuse3"),
         class = factor(class, ordered = TRUE))


```


```{r timothyPlotFunction}

plot_years_st <- function(spp = c("total"),
                       data = whap_su_years) {
  
  year_plots_st <- list()
  
  for (i in unique(data$LIT)) { 
    
    data_i <- data %>% dplyr::filter(LIT == i)
    
    year_plots_st[[i]] <-
                 ggplot(data = data_i %>% arrange(st_g_m2),
                        aes(x = Subunit_Name, 
                            y = st_g_m2,
                            color = year)) +
                 scale_color_manual(values = c("2019" = "deepskyblue",
                                               "2020" = "dodgerblue3",
                                               "2021" = "midnightblue")) +
                 labs(color = "year") +
                 # ggtitle("Comparison across years") +
                 geom_rect(data = ST_viaClass,
                           inherit.aes = FALSE,
                           aes(NULL,
                               NULL,
                               xmin = 0,
                               xmax = Inf,
                               fill = class),
                           ymin = unlist(ST_viaClass[, i]),
                           ymax = unlist(c(ST_viaClass[-1, i], Inf))) +
                 scale_fill_manual(values = alpha(c("red",
                                                    "yellow",
                                                    "chartreuse",
                                                    "chartreuse3"),
                                                  0.2)) +
                 geom_point(size = 3) +
                 xlab('Subunit\n') +
                 ylab("\nSwamp timothy seed head mass index (g/m^2)") +
                 geom_errorbar(aes(ymin = ifelse(CI80lwr_st < 0, 0, CI80lwr_st),
                                   ymax = CI80upr_st),
                               # CI's cut off below 0, impossible to have
                               # negative seed production values
                               width = 0.3,
                               cex = 0.75) +
                 theme(plot.title = element_text(size = 16, face = "bold"),
                       axis.ticks.y = element_blank(),
                       axis.text.x = element_text(face = "bold"),
                       axis.title = element_text(size = 12,
                                                 face = "bold"),
                       strip.text.y = element_text(hjust = 0,
                                                   vjust = 1,
                                                   angle = 180,
                                                   face = "bold")) +
                 coord_flip()
    print(year_plots_st[[i]])
  }
  return(year_plots_st)
}

plot_years_st()

```


```{r watergrassPlotFunction}

plot_years_wg <- function(spp = c("total"),
                       data = whap_su_years) {
  
  year_plots_wg <- list()
  
  for (i in unique(data$LIT)) { 
    
    data_i <- data %>% dplyr::filter(LIT == i)
    
    year_plots_wg[[i]] <-
                 ggplot(data = data_i %>% arrange(wg_g_m2),
                        aes(x = Subunit_Name,
                            y = wg_g_m2,
                            color = year)) +
                 scale_color_manual(values = c("2019" = "deepskyblue",
                                               "2020" = "dodgerblue3",
                                               "2021" = "midnightblue")) +
                 labs(color = "year") +
                 # ggtitle("Comparison across years") +
                 geom_rect(data = WG_viaClass,
                           inherit.aes = FALSE,
                           aes(NULL,
                               NULL,
                               xmin = -Inf,
                               xmax = Inf,
                               fill = class),
                           ymin = unlist(WG_viaClass[, i]),
                           ymax = unlist(c(WG_viaClass[-1, i], Inf))) +
                 scale_fill_manual(values = alpha(c("red",
                                                    "yellow",
                                                    "chartreuse",
                                                    "chartreuse3"),
                                                  0.2)) +
                 geom_point(size = 3) +
                 xlab('Subunit\n') +
                 ylab("\nWatergrass seed head mass index (g/m^2)") +
                 geom_errorbar(aes(ymin = ifelse(CI80lwr_wg < 0, 0, CI80lwr_wg),
                                   ymax = ifelse(CI80upr_wg > 100, 100, CI80upr_wg)),
                               # CI's cut off below 0, impossible to have
                               # negative seed production values
                               width = 0.3,
                               cex = 0.75) +
                 theme(plot.title = element_text(size = 16, face = "bold"),
                       axis.ticks.y = element_blank(),
                       axis.text.x = element_text(face = "bold"),
                       axis.title = element_text(size = 12,
                                                 face = "bold"),
                       strip.text.y = element_text(hjust = 0,
                                                   vjust = 1,
                                                   angle = 180,
                                                   face = "bold")) +
                 coord_flip()
    print(year_plots_wg[[i]])
  }
  return(year_plots_wg)
}

plot_years_wg()

```


```{r smartweedPlotFunction}

plot_years_sw <- function(spp = c("total"),
                       data = whap_su_years) {
  
  year_plots_sw <- list()
  
  for (i in unique(data$LIT)) {
    
    data_i <- data %>% dplyr::filter(LIT == i)
    
    year_plots_sw[[i]] <-
                 ggplot(data = data_i %>% arrange(sw_g_m2),
                        aes(x = Subunit_Name,
                            y = sw_g_m2,
                            color = year)) +
                 scale_color_manual(values = c("2019" = "deepskyblue",
                                               "2020" = "dodgerblue3",
                                               "2021" = "midnightblue")) +
                 # ggtitle("Comparison across years") +
                 geom_rect(data = SW_viaClass,
                           inherit.aes = FALSE,
                           aes(NULL,
                               NULL,
                               xmin = -Inf,
                               xmax = Inf,
                               fill = class),
                           ymin = unlist(SW_viaClass[, i]),
                           ymax = unlist(c(SW_viaClass[-1, i], Inf))) +
                 scale_fill_manual(values = alpha(c("red",
                                                    "yellow",
                                                    "chartreuse",
                                                    "chartreuse3"),
                                                  0.2)) +
                 geom_point(size = 3) +
                 xlab('Subunit\n') +
                 ylab("\nSmartweed seed head mass index (g/m^2)") +
                 geom_errorbar(aes(ymin = pmax(CI80lwr_sw, 0), 
                                   ymax = CI80upr_sw),
                               # CI's cut off below 0, impossible to have
                               # negative seed production values
                               width = 0.3,
                               cex = 0.75) +
                 theme(plot.title = element_text(size = 16, face = "bold"),
                       axis.ticks.y = element_blank(),
                       axis.text.x = element_text(face = "bold"),
                       axis.title = element_text(size = 12,
                                                 face = "bold"),
                       strip.text.y = element_text(hjust = 0,
                                                   vjust = 1,
                                                   angle = 180,
                                                   face = "bold")) +
                 coord_flip()
    print(year_plots_sw[[i]])
  }
  return(year_plots_sw)
}

plot_years_sw()

```


```{r barchart}

# load in files
kgLIT_2021 <- read.csv("WHAP2021-22/ScriptInput2021/mass_kg_LIT_2021.txt")

kgLIT_2020 <- read.csv("WHAP2020-21/ScriptInput2020/mass_kg_LIT_2020.txt")

kgLIT_2019 <- read.csv("MainScriptDataOutput/mass_kg_LIT_2019.txt")


# prep data
gm2_LIT <- bind_rows(kgLIT_2019, kgLIT_2020, kgLIT_2021) %>%
  mutate(year = factor(year),
         st_g.m2 = st_kg.ha / 10,
         wg_g.m2 = wg_kg.ha / 10,
         sw_g.m2 = sw_kg.ha / 10) %>%
  dplyr::select(LIT, st_g.m2, wg_g.m2, sw_g.m2, year) %>%
  pivot_longer(cols = ends_with("g.m2"),
               names_to = "species",
               values_to = "g.m2",
               values_drop_na = TRUE)

gm2_LIT$species[gm2_LIT$species == "st_g.m2"] <- "swamp timothy"

gm2_LIT$species[gm2_LIT$species == "wg_g.m2"] <- "watergrass"

gm2_LIT$species[gm2_LIT$species == "sw_g.m2"] <- "smartweed"

# gm2_LIT <- gm2_LIT[-c(14), ]


# plot the bar charts
plot_gm2_LIT <- function(data = gm2_LIT) {
  
  year_bar_plots <- list()
  
  for (i in unique(data$LIT)) {
    
    data_i <- data %>% dplyr::filter(LIT == i)
    
    year_bar_plots[[i]] <-
                 ggplot(data = data_i,
                        aes(x = species,
                            y = g.m2,
                            fill = year)) +
                 # ylim(0, 250) + #set the same y-axis range for KRN and PIX
                 geom_bar(stat="identity", position=position_dodge()) +
                 scale_fill_manual(values = c("2019" = "deepskyblue",
                                              "2020" = "blue",
                                              "2021" = "darkblue")) +
                 xlab('\nspecies') +
                 ylab("seed head mass index (g/m2)\n") +
                 theme_minimal()
                
    print(year_bar_plots[[i]])
  }
  return(year_bar_plots)
}

plot_gm2_LIT()


```

