---
title: "WHAPDataChecks2022"
output: html_document
---


```{r packages}

library(tidyverse)
library(magrittr)
```

# Valid file names

```{r file name check}

file_names <- list.files(path = "~/WHAP Data Analysis/WHAPDataAnalysis/WHAP_FinalCSV_20220309/2021")
str_detect(file_names, "WHAP_\\d\\d\\d\\d_VantagePolygons_\\d\\d\\d\\d\\d\\d\\d\\d")
str_detect(file_names, "WHAP_\\d\\d\\d\\d_CirclePlots_\\d\\d\\d\\d\\d\\d\\d\\d")
str_detect(file_names, "WHAP_\\d\\d\\d\\d_Quadrats_\\d\\d\\d\\d\\d\\d\\d\\d")
str_detect(file_names, "WHAP_\\d\\d\\d\\d_ManagementUnits_\\d\\d\\d\\d\\d\\d\\d\\d")

```

# read files

```{r read files}

vps0 <- read.csv("WHAP_FinalCSV_20220309/2021/WHAP_2021_VantagePolygons_20220309.csv")
cps0 <- read.csv("WHAP_FinalCSV_20220309/2021/WHAP_2021_CirclePlots_20220309.csv")
qdt0 <- read.csv("WHAP_FinalCSV_20220309/2021/WHAP_2021_Quadrats_20220309.csv")
mus0 <- read.csv("WHAP_FinalCSV_20220309/2021/WHAP_2021_ManagementUnits_20220309.csv")

```

# valid column names

```{r column name check}

## vantage polygons
vps_cols <- sort(c("areaVisible",
                   "decimalLatitude",
                   "decimalLongitude",
                   "eventDate",
                   "eventRemarks",
                   "GlobalID_VP",
                   "LIT",
                   "noFoodVisible",
                   "proportionVisibleArea",
                   "recordedBy",
                   "stratum",
                   "subunitName",
                   "taxonID",
                   "unitName", 
                   "vernacularName"))
                   
setdiff(names(vps0), vps_cols)

## circle plots
cps_cols <- sort(c("decimalLatitude",
                   "decimalLongitude",
                   "eventDate",
                   "eventRemarks",
                   "GlobalID_CP",
                   "LIT",
                   "noFoodVisible",
                   "plotStatus",
                   "proportionVisibleArea",
                   "recordedBy",
                   "stratum",
                   "subunitName",
                   "taxonID",
                   "unitName", 
                   "vernacularName"))

setdiff(names(cps0), cps_cols)

## quadrats
qdt_cols <- sort(c("decimalLatitude",
                   "decimalLongitude",
                   "distanceCP_m",
                   "distanceVP_m",
                   "eventDate",
                   "eventRemarks",
                   "GlobalID_CP",
                   "GlobalID_Qdt",
                   "GlobalID_seed",
                   "GlobalID_VP",
                   "LIT", 
                   "managementAction",
                   "measurementType",
                   "measurementValue",
                   "nSeedHeads",
                   "plantHeight",
                   "quadratSize",
                   "recordedBy", 
                   "stratum",
                   "subunitName",
                   "taxonID",
                   "unitName", 
                   "vernacularName"))

setdiff(names(qdt0), qdt_cols)

## management units
mus_cols <- sort(c("acreage",
                   "LIT",
                   "refugeName",
                   "subunitName",
                   "unitName"))

setdiff(names(mus0), mus_cols)

```

# valid names within columns

```{r valid column entries}
## vernacularName
vernac_names <- sort(c("Other cover", "Watergrass", "Swamp Timothy",
                       "Smartweed"))

## LIT codes
LIT_codes <- sort(c("KRN", "PIX", "MDC", "SAC", "SLW", "CLS"))

## stratum
strata <- sort(c("high", "medium", "low", "NA"))

## taxonID
taxonIDs <- sort(c("41605", "502210", "823756"))

## plotStatus
plot_status <- sort(c("Complete", "Inaccessible", "NoFoodVisible"))

## managementAction
mgt_actions <- sort(c("mowed", "none"))

## measurementType
meas_types <- sort(c("sh_length_mm", "sh_width_mm", "f2t_length_mm"))

## quadratSize
qdt_sizes <- sort(c("15x15cm", "30x30cm", "5x5cm"))

## refugeName
refuge_names <- sort(c("STONE LAKES NATIONAL WILDLIFE REFUGE",
                       "MODOC NATIONAL WILDLIFE REFUGE",
                       "PIXLEY NATIONAL WILDLIFE REFUGE",
                       "KERN NATIONAL WILDLIFE REFUGE"))

## unitName
unit_names <- sort(c("Lewis 1",
                     "Lewis 6",
                     "HQ-7",
                     "LIC",
                     "Beach Lake 3",
                     "Beach Lake 1",
                     "HQ-6",
                     "Lewis 2",
                     "Beach Lake 2",
                     "HQ-5",
                     "Grandma Tract 10",
                     "Grandma Tract 2",
                     "Grandma Tract 3",
                     "Grandma Tract 4",
                     "Grandma Tract 7",
                     "Grandma Tract 8",
                     "Grandma Tract 9",
                     "Grandma Tract 11",
                     "Gadwall",
                     "J Pond",
                     "House Field",
                     "Matney 3",
                     "Matney 4 North",
                     "Matney 8",
                     "South Dam Pond",
                     "Matney 6",
                     "Matney 4 South",
                     "Matney 7",
                     "Flournoy Pond",
                     "Duck Ponds",
                     "Upper Goose Pond",
                     "Lower Goose Pond",
                     "Middle Goose Pond",
                     "1",
                     "8B",
                     "6",
                     "7A",
                     "9A",
                     "9B",
                     "8A",
                     "7B",
                     "4",
                     "4A",
                     "3A",
                     "3",
                     "2",
                     "2A",
                     "14",
                     "6A",
                     "5B",
                     "5A",
                     "4B"))

## subunitName
subunit_names <- sort(c("22",
                        "27a",
                        "57",
                        "Beach Lake 3",
                        "Beach Lake 1",
                        "HQ-6",
                        "Lewis 2",
                        "Beach Lake 2",
                        "HQ-5",
                        "Grandma Tract 10",
                        "Grandma Tract 2",
                        "Grandma Tract 3",
                        "Grandma Tract 4",
                        "Grandma Tract 7",
                        "Grandma Tract 8",
                        "Grandma Tract 9",
                        "Grandma Tract 11",
                        "Gadwall",
                        "J Pond",
                        "House Field",
                        "Matney 3",
                        "Matney 4 North",
                        "Matney 8",
                        "South Dam Pond",
                        "Matney 6",
                        "Matney 4 South",
                        "Matney 7",
                        "Flournoy Pond",
                        "Duck Ponds",
                        "Upper Goose Pond",
                        "Lower Goose Pond",
                        "Middle Goose Pond",
                        "1",
                        "8B",
                        "6",
                        "7A",
                        "9A",
                        "9B",
                        "8A",
                        "7B",
                        "4",
                        "4A",
                        "3A",
                        "3",
                        "2",
                        "2A",
                        "14-A",
                        "14-B",
                        "14-C",
                        "14-D",
                        "14-E",
                        "14-F",
                        "14-G",
                        "4A-1",
                        "4A-2",
                        "4A-3",
                        "4A-4",
                        "4A-5",
                        "4A-6",
                        "4A-7",
                        "4B-1",
                        "4B-2",
                        "4B-3",
                        "4B-4",
                        "5A-1",
                        "5A-3",
                        "5A-4",
                        "5A-5",
                        "5A-6",
                        "5A-7",
                        "5B-1",
                        "5B-2",
                        "5B-3",
                        "5B-5",
                        "5B-6",
                        "5B-7",
                        "5B-8",
                        "6A-1",
                        "6A-2",
                        "6A-3",
                        "6A-4",
                        "6A-5"))
```

```{r check column entries}

# check vernacular names
setdiff(unique(vps0$vernacularName), vernac_names)
setdiff(unique(cps0$vernacularName), vernac_names)
setdiff(unique(qdt0$vernacularName), vernac_names)

# check LIT codes 
setdiff(unique(vps0$LIT), LIT_codes)
setdiff(unique(cps0$LIT), LIT_codes)
setdiff(unique(qdt0$LIT), LIT_codes)
setdiff(unique(mus0$LIT), LIT_codes)

# check strata
setdiff(unique(vps0$stratum), strata)
setdiff(unique(cps0$stratum), strata)
setdiff(unique(qdt0$stratum), strata)

# check Taxon ID
setdiff(unique(vps0$taxonID), taxonIDs)
setdiff(unique(cps0$taxonID), taxonIDs)
setdiff(unique(qdt0$taxonID), taxonIDs)

# check plot status
setdiff(unique(cps0$plotStatus), plot_status)

# check management actions
setdiff(unique(qdt0$managementAction), mgt_actions)

# check measurement type
setdiff(unique(qdt0$measurementType), meas_types)

# check quadrat size
setdiff(unique(qdt0$quadratSize), qdt_sizes)

# check refuge name
setdiff(unique(mus0$refugeName), refuge_names)

# check unit names 
setdiff(unique(vps0$unitName), unit_names)
setdiff(unique(cps0$unitName), unit_names)
setdiff(unique(qdt0$unitName), unit_names)
setdiff(unique(mus0$unitName), unit_names)

# check subunit names
setdiff(unique(vps0$subunitName), subunit_names)
setdiff(unique(cps0$subunitName), subunit_names)
setdiff(unique(qdt0$subunitName), subunit_names)
setdiff(unique(mus0$subunitName), subunit_names)



```

